# Generated by Django 4.2.9 on 2024-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0003_alter_dailyprice_close_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='shares_traded',
            field=models.IntegerField(null=True),
        ),
    ]
