# Generated by Django 4.2.9 on 2024-01-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0004_alter_dailyprice_shares_traded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nse_app.index'),
        ),
    ]
